#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.36245
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WorkEX.Resource", IsApplication=true)]

namespace WorkEX
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ActionSave = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int splash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000f
			public const int NameText = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int NotesText = 2131165198;
			
			// aapt resource value: 0x7f070002
			public const int btnAddBids = 2131165186;
			
			// aapt resource value: 0x7f070007
			public const int editText1 = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int editText2 = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int editText3 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int editText4 = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int editText5 = 2131165194;
			
			// aapt resource value: 0x7f070004
			public const int linearLayout1 = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout2 = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout3 = 2131165184;
			
			// aapt resource value: 0x7f070012
			public const int listView1 = 2131165202;
			
			// aapt resource value: 0x7f07000d
			public const int lstItemTask = 2131165197;
			
			// aapt resource value: 0x7f070014
			public const int menu_add = 2131165204;
			
			// aapt resource value: 0x7f070010
			public const int myButton = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int progressBarMain = 2131165201;
			
			// aapt resource value: 0x7f070003
			public const int scrollView1 = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int spinner1 = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int textView1 = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int textView2 = 2131165192;
			
			// aapt resource value: 0x7f070013
			public const int webView1 = 2131165203;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LAddBids = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int listBids = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int splash = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int MainMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
